name: ESLint Rule CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Eslint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Lint source files
        run: npx eslint .

      - name: Lint fix source files
        run: npx eslint . --fix
    
  Publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    needs: Eslint
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          registry-url: https://npm.pkg.github.com/

      - name: Install dependencies
        run: npm install

      - name: Bump Version
        run: npm version patch --no-git-tag-version

      
      - name: Authenticate with GitHub Packages
        run: 
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          echo "@kristinnfb:registry=https://npm.pkg.github.com/" >> ~/.npmrc

      - name: Publish to GitHub Packages
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
