name: ESLint Rule CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
        
    - name: Use Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: 20
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
      
    - name: Lint source files
      run: npm run lint
      
    - name: Run tests
      run: npm run test
      
    - name: Publish to npm
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}